### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Frank-Buss** [Maaack/Godot-Menus-Template#18]
I tried it with Godot 4.2.2, and I get a compile error: 
![Screenshot_20240706_030743](https://github.com/Maaack/Godot-Menus-Template/assets/55055211/3860ad7c-bd4e-4bc6-b651-139ac60af4b3)

**Comment by Maaack** [comment]
I started a new project, installed Maaack's Menus Template, restarted Godot, activated the plugin, copied the template, ran the project, and opened the scene in question. At no point could I reproduce this error.

Maybe this will help:
https://www.youtube.com/watch?v=-QWJnZ8bVdk

**Comment by Frank-Buss** [comment]
Thanks, works here, too, with a new project. I think the problem was that I imported both, your menu plugin and the game template plugin.
