### ISSUE TITLE
Error at (15, 5): Identifier "SceneLoader" not declared in the current scope.

### ISSUE THREAD

**Issue by echoless3484** [Maaack/Godot-Menus-Template#4]
Error at (15, 5): Identifier "SceneLoader" not declared in the current scope.
Error at (18, 5): Identifier "SceneLoader" not declared in the current scope.

Hey there, I'm still quite new to Godot and I've never had this error before, this is with MainMenu.gd and only happens after I made it the main scene, can't quite figure out what's happening and I don't even know what the error really means...

The project also isn't letting me move the menus template out of Addons, help for that would also be greatly appreciated 😅

**Comment by echoless3484** [comment]
🤣 just turns out I can't follow instructions, disregard the first part but the moving out of the addons folder is still a problem

**Comment by echoless3484** [comment]
![image](https://github.com/Maaack/Godot-Menus-Template/assets/109392419/21abb5d8-8b1c-471d-b7e6-094755fd1a11)
???

**Comment by Maaack** [comment]
> 🤣 just turns out I can't follow instructions, disregard the first part but the moving out of the addons folder is still a problem

Good to know the first part resolved itself. I'm working on an improvement to the plugin that will help with copying the contents over, as there's a little more to it than copy + paste. I expect I'll have it released by the end of this week.

**Comment by Maaack** [comment]
> ![image](https://private-user-images.githubusercontent.com/109392419/326292396-21abb5d8-8b1c-471d-b7e6-094755fd1a11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDAyMDMsIm5iZiI6MTcxNDMzOTkwMywicGF0aCI6Ii8xMDkzOTI0MTkvMzI2MjkyMzk2LTIxYWJiNWQ4LThiMWMtNDcxZC1iN2U2LTA5NDc1NWZkMWExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQyMTMxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDYwZTJmOWM2ZTAyOWZmN2ZkMTQxMzk0ZmU2ODc3MDIwMjAzMmEzNjg0NWY1YmM4ODE5NmZjODY1MjU1MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7XBLr6KOi14r2B8Np9oUHFGqzyiVDQKjQzsgcr4lWyc) ???

I'd check that the plugin is enabled, and the autoloads are installed. If yes to both, then I'd try reloading Godot. If it's still an issue, then let me know.

**Comment by echoless3484** [comment]
> > ![image](https://private-user-images.githubusercontent.com/109392419/326292396-21abb5d8-8b1c-471d-b7e6-094755fd1a11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDAyMDMsIm5iZiI6MTcxNDMzOTkwMywicGF0aCI6Ii8xMDkzOTI0MTkvMzI2MjkyMzk2LTIxYWJiNWQ4LThiMWMtNDcxZC1iN2U2LTA5NDc1NWZkMWExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQyMTMxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDYwZTJmOWM2ZTAyOWZmN2ZkMTQxMzk0ZmU2ODc3MDIwMjAzMmEzNjg0NWY1YmM4ODE5NmZjODY1MjU1MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7XBLr6KOi14r2B8Np9oUHFGqzyiVDQKjQzsgcr4lWyc) ???
> 
> I'd check that the plugin is enabled, and the autoloads are installed. If yes to both, then I'd try reloading Godot. If it's still an issue, then let me know.

Got it, thanks!

**Comment by Maaack** [comment]
> The project also isn't letting me move the menus template out of Addons, help for that would also be greatly appreciated 😅

The package is now updated in the Godot Asset Library to include example files and a tool to copy them out of the addons/ folder. Feel free to post new issues if you have additional feedback.

**Comment by echoless3484** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by echoless3484** [comment]
Would love some documentation on adding more settings, tabs and menus, like if I want to add an anti-aliasing setting, how would I add it and how would I make the setting save, chances are people using this are using it to learn as they are beginners and templates like this really help!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
